name: build-latest

on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [build-latest]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - name: Install goss and dgoss
        run: |
          curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o $HOME/goss
          chmod +rx $HOME/goss
          curl -L https://github.com/aelsabbahy/goss/releases/latest/download/dgoss -o $HOME/dgoss
          chmod +rx $HOME/dgoss
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Add HOME directory to PATH
        run: echo "$HOME" >> $GITHUB_PATH
      - name: Build and test image
        run: ./build-latest.sh ${{ secrets.BASE_IMAGE }} ${{ secrets.BASE_IMAGE_VERSION }}
      - name: Publish image
        run: docker push taconsol/sakuli-remote-connection:latest